# Generated by Django 2.2.3 on 2023-01-14 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='名字')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('topic', models.CharField(max_length=50, verbose_name='主题')),
                ('text', models.TextField(verbose_name='内容')),
                ('created_time', models.DateTimeField(verbose_name='评论时间')),
            ],
            options={
                'verbose_name': '联系',
                'verbose_name_plural': '联系',
                'ordering': ['-created_time'],
            },
        ),
    ]
